name: echo2ui 
base: core20 
version: '0.1'
summary: echoing to UI whenever required 
description: |
  echo2ui utilize x11 utils to let you deliver informational messages to user using xterm as UI widget and whiptail as agent.
  run: echo2ui -e bash -c "whiptail --msgbox 'MESSAGE: delivering straing from $SNAP_NAME snap' 10 20".

grade: stable 
confinement: strict 

apps:
  echo2ui:
   command: bin/echo2ui
   plugs:
        - desktop
        - desktop-legacy
        - opengl
        - unity7
        - x11
        - wayland
parts:
  xterm:
    stage-packages:
        # apps
        - xterm
        - whiptail
    plugin: nil
  echo2ui:
    plugin: dump
    source: src/
