name: echo2ui 
base: core20 
version: '0.1'
summary: echoing to UI on app crash  
description: |
  crash2ui utilize echo2ui utils to let you deliver informational messages to user using stterm as UI widget and whiptail as agent.

grade: stable 
confinement: strict 

apps:
  launcher:
   command: bin/launcher
   plugs:
        - desktop
        - desktop-legacy
        - opengl
        - unity7
        - x11
        - wayland
        - home
  crash2ui:
   command: bin/launcher $SNAP/bin/crash.sh
   plugs:
        - desktop
        - desktop-legacy
        - opengl
        - unity7
        - x11
        - wayland
        - home
  echo2ui:
   command: bin/echo2ui
   plugs:
        - desktop
        - desktop-legacy
        - opengl
        - unity7
        - x11
        - wayland
        - home
parts:
  apps:
    stage-packages:
        #- stterm 
        - xterm
        - whiptail
    plugin: nil
  echo2ui:
    plugin: dump
    source-type: local
    source: src/
  bash-crash:
    plugin: dump
    source-type: local
    source: BashCrashExample/
