name: echo2ui 
base: core20 
version: '0.1'
summary: echoing to UI on app crash  
description: |
  echo2ui is collection of launcher scripts which redirects the stdout & stderr channel of program launched via them to userland using minimal GUI X11-utils.

grade: stable 
confinement: strict 
compression: lzo

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  echo2ui:
   command: bin/echo2ui
   plugs: &allplugs
     - desktop
     - desktop-legacy
     - opengl
     - unity7
     - x11
     - wayland
     - home

  launcher:
   command: bin/launcher
   plugs: *allplugs

  bashCrash2ui:
   command: bin/launcher $SNAP/bin/crash.sh
   plugs: *allplugs

  qtCrash2ui:
   command: bin/launcher $SNAP/bin/crash
   plugs: *allplugs

parts:
  utils:
    stage-packages:
        - xterm
        - whiptail
    plugin: nil
  echo2ui:
    plugin: dump
    source-type: local
    source: src/
  bash-crash:
    plugin: dump
    source-type: local
    source: BashCrashExample/
  qt-crash:
    plugin: dump
    source-type: local
    source: QtCrashExample/crash/
    organize:
      crash: bin/crash
